### ISSUE TITLE
Modify GUIHandler.launchGame() to have a PieceType parameter to know which PieceType to create the GamePlayer with

### ISSUE THREAD

**Issue by jau35** [jau35/CS451#3]
The launchGame method in the GUIHandler class is used to set up the window for the game and initialize the GamePlayer object. Modify this method and the initGame method to accept a PieceType so it knows what type to initialize the GamePlayer with (right now it is hardcoded to black).

```
public void launchGame(PieceType pieceType) {
     initGame(pieceType);
     refresh();
}

public void initGame(PieceType pieceType) {
     ...
     GamePlayer gp = new GamePlayer(network, (CheckersPanel) jpleft, pieceType); 
     ...
}
```

The launchGame method will be called in two different situations.
1. The user accepts an invitation
2. An invitation the user sent was accepted
 
One of these should call launchGame with PieceType.RED, the other with PieceType.BLACK

**Comment by dmp359** [comment]
Oh yeah forgot its hardcoded

**Comment by dmp359** [comment]
I have a few questions on this. I'll ask you in person.
