### ISSUE TITLE
Add a new MessageBody type to represent chat messages

### ISSUE THREAD

**Issue by jau35** [jau35/CS451#58]
Add ChatMessageBody that extends MessageBody.

It should encode and decode JSON in the format:
```
{
   “user” : “MartyMcFly”,
   “time” : “yyyy-MM-dd HH:mm a z”,
   “message” : “Good luck!”
}
```

**Comment by dmp359** [comment]
Not sure why we need the time of the message. We're not printing it.

**Comment by jau35** [comment]
I just copied/pasted from the design doc. It's there if we need it

**Comment by dmp359** [comment]
I know. Just wondering.

**Comment by jau35** [comment]
Modified chatmessagebody to only have the username and message. removed time field
